apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: scheduler
    tier: control-plane
    name: kube-scheduler
  name: kube-scheduler
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: scheduler
  replicas: 1
  template:
    metadata:
      labels:
        component: scheduler
        tier: control-plane
      name: kube-scheduler
    spec:
      containers:
        - command:
            - /usr/local/bin/kube-scheduler
            - --address=0.0.0.0
            - --leader-elect=true
            - --scheduler-name=kube-scheduler-extender
            - --policy-configmap=policy-config
            - --policy-configmap-namespace=kube-system
            - --lock-object-name=kube-scheduler-extender
          image: zhangzhonglin/kube-scheduler-amd64:v1.16.2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10251
            initialDelaySeconds: 15
          name: stork-scheduler
          readinessProbe:
            httpGet:
              path: /healthz
              port: 10251
          resources:
            requests:
              cpu: '0.1'
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "name"
                    operator: In
                    values:
                      - kube-scheduler
              topologyKey: "kubernetes.io/hostname"
      hostPID: false
      serviceAccountName: kube-scheduler-account
